export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { cleanText, getClientIp, jsonError, requireActorApi } from '@/lib/apiSecurity';
import { createAdminClient } from '@/lib/supabase/admin';
import { writeAuditLog } from '@/lib/audit';

const READ_ROLES = ['super_admin', 'operations_admin', 'finance', 'support'] as const;
const WRITE_ROLES = ['super_admin', 'operations_admin', 'finance'] as const;
const BUCKET = 'service-uploads';
type ApiPayload = Record<string, unknown>;
type Warranty = Record<string, unknown>;
type CompanySettings = Record<string, unknown>;

function isUuid(value: string | null | undefined) {
  return Boolean(value && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value));
}

function pdfEscape(value: unknown) {
  return String(value ?? '').replace(/[\\()]/g, (match) => `\\${match}`).slice(0, 180);
}

function safePath(value: string) {
  return value.replace(/[^a-z0-9_.-]/gi, '-').replace(/-+/g, '-').slice(0, 120) || 'warranty';
}

function settingText(settings: CompanySettings, key: string, fallback = '') {
  const value = settings[key];
  return typeof value === 'string' && value.trim() ? value.trim() : fallback;
}

function buildSimplePdf(lines: string[]) {
  const textOps = lines.slice(0, 44).map((line, index) => `BT /F1 ${index === 0 ? 15 : index === 8 ? 13 : 9} Tf 45 ${795 - index * 17} Td (${pdfEscape(line)}) Tj ET`).join('\n');
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(textOps)} >> stream\n${textOps}\nendstream endobj`
  ];
  let body = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(body));
    body += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { body += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  body += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(body, 'utf8');
}

function buildWarrantyPdf(warranty: Warranty, settings: CompanySettings) {
  const companyName = settingText(settings, 'company_name', 'NANOFIX');
  const tagline = settingText(settings, 'company_tagline', 'No-Hacking Leak Repair & Waterproofing Solutions');
  const uen = settingText(settings, 'uen');
  const gst = settingText(settings, 'gst_registration_no');
  const phone = settingText(settings, 'phone', '+65 8038 7877');
  const whatsapp = settingText(settings, 'whatsapp', '+65 8038 7877');
  const email = settingText(settings, 'email');
  const website = settingText(settings, 'website', 'https://www.nanofixsg.com');
  const warrantyFooter = settingText(settings, 'warranty_footer', 'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.');
  const termsFooter = settingText(settings, 'terms_footer', 'This document is system-generated by NANOFIX Service Operations.');
  const coverage = warranty.coverage || warranty.terms_snapshot || 'NANOFIX standard workmanship warranty.';
  const terms = warranty.terms_snapshot || warranty.coverage || warrantyFooter;
  const lines = [
    companyName.toUpperCase(),
    tagline,
    uen ? `UEN: ${uen}` : '',
    gst ? `GST Reg No: ${gst}` : '',
    `Phone: ${phone}    WhatsApp: ${whatsapp}`,
    email ? `Email: ${email}` : '',
    `Website: ${website}`,
    '',
    'SERVICE WARRANTY CERTIFICATE',
    `Warranty ID: ${pdfEscape(warranty.warranty_id)}`,
    `Customer ID: ${pdfEscape(warranty.customer_id)}`,
    `Job ID: ${pdfEscape(warranty.job_id)}`,
    `Source Quotation ID: ${pdfEscape(warranty.source_quotation_id)}`,
    `Source Acceptance ID: ${pdfEscape(warranty.source_acceptance_id)}`,
    `Source Invoice ID: ${pdfEscape(warranty.source_invoice_id)}`,
    `Warranty Years: ${pdfEscape(warranty.warranty_years)}`,
    `Status: ${pdfEscape(warranty.status)}`,
    `Start Date: ${pdfEscape(warranty.starts_at)}`,
    `End Date: ${pdfEscape(warranty.ends_at)}`,
    `Generation Source: ${pdfEscape(warranty.generation_source)}`,
    `Generated At: ${pdfEscape(warranty.generated_at || warranty.created_at)}`,
    '',
    'Coverage:',
    pdfEscape(coverage),
    '',
    'Warranty Terms Snapshot:',
    pdfEscape(terms),
    '',
    'Important Notes:',
    'Warranty coverage follows the confirmed quotation/order scope and actual completed repair works.',
    'Any new issue outside the approved scope may require inspection and separate quotation.',
    '',
    'Terms:',
    warrantyFooter,
    termsFooter
  ].filter(Boolean);
  return buildSimplePdf(lines);
}

async function loadSettings() {
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('document_company_settings')
    .select('setting_id,company_name,company_tagline,uen,gst_registration_no,phone,whatsapp,email,website,warranty_footer,terms_footer')
    .eq('setting_key', 'nanofix_default')
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data ?? { company_name: 'NANOFIX', company_tagline: 'No-Hacking Leak Repair & Waterproofing Solutions', phone: '+65 8038 7877', whatsapp: '+65 8038 7877', website: 'https://www.nanofixsg.com' };
}

async function loadWarranty(warrantyId: string) {
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('warranties')
    .select('warranty_id,job_id,customer_id,status,coverage,starts_at,ends_at,warranty_years,source_quotation_id,source_acceptance_id,source_invoice_id,auto_generated,generation_source,generated_at,terms_snapshot,metadata_json,pdf_storage_path,visible_to_customer,created_at')
    .eq('warranty_id', warrantyId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error('Warranty not found.');
  return data as Warranty;
}

export async function GET(request: NextRequest) {
  const auth = await requireActorApi(request, [...READ_ROLES]);
  if (!auth.ok) return auth.response;
  const warrantyId = cleanText(request.nextUrl.searchParams.get('warranty_id'), 120);
  if (!isUuid(warrantyId)) return jsonError('Valid warranty_id is required.', 400);
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('warranty_pdf_documents')
    .select('warranty_pdf_id,warranty_id,job_id,customer_id,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,generation_notes,created_at')
    .eq('warranty_id', warrantyId)
    .order('created_at', { ascending: false })
    .limit(20);
  if (error) return jsonError(error.message, 500);
  await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_warranty_pdfs_read', objectType: 'warranty', objectId: warrantyId, after: { count: data?.length ?? 0 }, ip: getClientIp(request) }).catch(() => undefined);
  return NextResponse.json({ ok: true, warranty_pdfs: data ?? [] });
}

export async function POST(request: NextRequest) {
  const auth = await requireActorApi(request, [...WRITE_ROLES]);
  if (!auth.ok) return auth.response;
  const body = await request.json().catch(() => ({})) as ApiPayload;
  const action = cleanText(body.action, 100);
  const warrantyId = cleanText(body.warranty_id, 120);
  if (action !== 'generate_warranty_pdf') return jsonError('Unsupported warranty PDF action.', 400);
  if (!isUuid(warrantyId)) return jsonError('Valid warranty_id is required.', 400);

  const visibleToCustomer = body.visible_to_customer !== false;
  const notes = cleanText(body.generation_notes, 1000) || 'Warranty PDF generated from Service Operations.';
  const supabase = createAdminClient();

  try {
    const [warranty, settings] = await Promise.all([loadWarranty(warrantyId), loadSettings()]);
    const pdf = buildWarrantyPdf(warranty, settings);
    const fileRef = `NANOFIX-WARRANTY-${safePath(warrantyId)}`;
    const storagePath = `service-operations/warranties/${safePath(warrantyId)}/${Date.now()}-${fileRef}.pdf`;
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(storagePath, pdf, { contentType: 'application/pdf', upsert: false });
    if (uploadError) throw new Error(uploadError.message);

    const { data: doc, error: docError } = await supabase
      .from('warranty_pdf_documents')
      .insert({
        warranty_id: warrantyId,
        job_id: typeof warranty.job_id === 'string' ? warranty.job_id : null,
        customer_id: typeof warranty.customer_id === 'string' ? warranty.customer_id : null,
        storage_bucket: BUCKET,
        storage_path: storagePath,
        file_name: `${fileRef}.pdf`,
        file_size_bytes: pdf.byteLength,
        generation_status: 'uploaded',
        visible_to_customer: visibleToCustomer,
        generated_by: auth.actor.profileId,
        generation_notes: notes,
        metadata_json: { template: 'nanofix_warranty_certificate_v1', company_setting_id: settings.setting_id ?? null, warranty_years: warranty.warranty_years, source_quotation_id: warranty.source_quotation_id ?? null, source_acceptance_id: warranty.source_acceptance_id ?? null, source_invoice_id: warranty.source_invoice_id ?? null }
      })
      .select('warranty_pdf_id,warranty_id,job_id,customer_id,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,created_at')
      .single();
    if (docError) throw new Error(docError.message);

    const { data: updatedWarranty, error: warrantyError } = await supabase
      .from('warranties')
      .update({ pdf_storage_path: storagePath, visible_to_customer: visibleToCustomer, customer_visible_at: visibleToCustomer ? new Date().toISOString() : null, customer_visible_by: visibleToCustomer ? auth.actor.profileId : null, customer_visibility_notes: notes })
      .eq('warranty_id', warrantyId)
      .select('warranty_id,job_id,customer_id,status,coverage,warranty_years,starts_at,ends_at,source_quotation_id,source_acceptance_id,source_invoice_id,generation_source,visible_to_customer,pdf_storage_path,customer_visible_at,customer_visible_by,created_at')
      .single();
    if (warrantyError) throw new Error(warrantyError.message);

    const { data: task, error: taskError } = await supabase.from('unified_tasks').insert({
      source_module: 'service_operations',
      source_table: 'warranty_pdf_documents',
      source_id: doc.warranty_pdf_id,
      title: 'Warranty PDF generated',
      description: `Warranty PDF generated for warranty ${warrantyId}.`,
      priority: 'P2',
      assignee_role: 'operations_admin',
      status: 'open',
      metadata_json: { warranty_id: warrantyId, storage_path: storagePath, template: 'nanofix_warranty_certificate_v1' }
    }).select('task_id,source_module,source_table,source_id,title,status,priority,assignee_role,created_at').single();
    if (taskError) throw new Error(taskError.message);
    await supabase.from('task_events').insert({ task_id: task.task_id, action: 'warranty_pdf_generated', after_json: { warranty_pdf: doc, warranty: updatedWarranty } }).throwOnError();
    await supabase.from('internal_inbox_messages').insert({ recipient_role: 'operations_admin', subject: 'Warranty PDF generated', body: `Warranty PDF generated for warranty ${warrantyId}.`, category: 'warranty_pdf', priority: 'P2', related_object_type: 'warranty_pdf_document', related_object_id: doc.warranty_pdf_id, task_id: task.task_id }).throwOnError();

    if (visibleToCustomer && updatedWarranty.customer_id) {
      await supabase.from('notification_outbox').insert({ channel: 'internal', recipient_customer_id: updatedWarranty.customer_id, subject: 'NANOFIX warranty certificate is ready', body: 'Your NANOFIX warranty certificate PDF is ready in Customer Portal.', payload_json: { source: 'warranty_pdf_generator', warranty_id: warrantyId, storage_path: storagePath }, delivery_status: 'queued', related_object_type: 'warranty', related_object_id: warrantyId }).throwOnError();
    }

    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_warranty_pdf_generate', objectType: 'warranty', objectId: warrantyId, after: { warranty_pdf: doc, warranty: updatedWarranty, task }, ip: getClientIp(request) }).catch(() => undefined);
    return NextResponse.json({ ok: true, warranty_pdf: doc, warranty: updatedWarranty, task }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_warranty_pdf_generate_failed', objectType: 'warranty', objectId: warrantyId, after: { error: message }, ip: getClientIp(request) }).catch(() => undefined);
    return jsonError(message, 500);
  }
}
