'use client';

import { FormEvent, useEffect, useState } from 'react';

type Settings = Record<string, unknown>;
type State = { loading: boolean; error: string | null; message: string | null; settings: Settings | null; result: Record<string, unknown> | null };

type Values = {
  company_name: string;
  company_tagline: string;
  uen: string;
  gst_registration_no: string;
  address_line_1: string;
  address_line_2: string;
  phone: string;
  whatsapp: string;
  email: string;
  website: string;
  logo_storage_path: string;
  invoice_prefix: string;
  quotation_prefix: string;
  payment_instructions: string;
  warranty_footer: string;
  terms_footer: string;
  primary_color: string;
  secondary_color: string;
};

const inputClass = 'rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-800 outline-none focus:border-activeBlue focus:ring-2 focus:ring-blue-100';

const defaults: Values = {
  company_name: 'NANOFIX',
  company_tagline: 'No-Hacking Leak Repair & Waterproofing Solutions',
  uen: '',
  gst_registration_no: '',
  address_line_1: '',
  address_line_2: '',
  phone: '+65 8038 7877',
  whatsapp: '+65 8038 7877',
  email: '',
  website: 'https://www.nanofixsg.com',
  logo_storage_path: '',
  invoice_prefix: 'NFX-INV',
  quotation_prefix: 'NFX-QUO',
  payment_instructions: 'Please make payment using the payment link provided in Customer Portal or contact NANOFIX for bank transfer instructions.',
  warranty_footer: 'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.',
  terms_footer: 'This document is system-generated by NANOFIX Service Operations. All prices are in SGD unless otherwise stated.',
  primary_color: '#FF5F00',
  secondary_color: '#1E293B'
};

function toValues(settings: Settings | null): Values {
  if (!settings) return defaults;
  return Object.fromEntries(Object.keys(defaults).map((key) => [key, typeof settings[key] === 'string' ? settings[key] as string : defaults[key as keyof Values]])) as Values;
}

async function loadSettings() {
  const response = await fetch('/api/admin/service-operations/document-settings', { credentials: 'same-origin', cache: 'no-store' });
  const text = await response.text();
  let payload: { ok?: boolean; error?: string; settings?: Settings } | null = null;
  try { payload = text ? JSON.parse(text) as { ok?: boolean; error?: string; settings?: Settings } : null; } catch { payload = null; }
  if (!response.ok || payload?.ok === false) throw new Error(payload?.error ?? `Document settings API returned ${response.status}`);
  return payload?.settings ?? null;
}

async function saveSettings(values: Values) {
  const response = await fetch('/api/admin/service-operations/document-settings', {
    method: 'POST',
    credentials: 'same-origin',
    cache: 'no-store',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ action: 'save_document_company_settings', ...values, is_active: true })
  });
  const text = await response.text();
  let payload: Record<string, unknown> | null = null;
  try { payload = text ? JSON.parse(text) as Record<string, unknown> : null; } catch { payload = null; }
  if (!response.ok || payload?.ok === false) throw new Error(typeof payload?.error === 'string' ? payload.error : `Document settings save returned ${response.status}`);
  return payload ?? { ok: true };
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="grid gap-1 text-xs font-black uppercase tracking-[0.08em] text-slate-500">{label}<input className={inputClass} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="grid gap-1 text-xs font-black uppercase tracking-[0.08em] text-slate-500 md:col-span-2">{label}<textarea className={inputClass} rows={3} value={value} onChange={(event) => onChange(event.target.value)} /></label>;
}

export function ServiceOperationsDocumentSettingsPanel() {
  const [values, setValues] = useState<Values>(defaults);
  const [state, setState] = useState<State>({ loading: true, error: null, message: null, settings: null, result: null });

  function change(key: keyof Values, value: string) {
    setValues((current) => ({ ...current, [key]: value }));
  }

  async function refresh() {
    setState((current) => ({ ...current, loading: true, error: null, message: null }));
    try {
      const settings = await loadSettings();
      setValues(toValues(settings));
      setState({ loading: false, error: null, message: null, settings, result: null });
    } catch (error) {
      setState((current) => ({ ...current, loading: false, error: error instanceof Error ? error.message : String(error) }));
    }
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setState((current) => ({ ...current, loading: true, error: null, message: null, result: null }));
    try {
      const result = await saveSettings(values);
      const settings = typeof result.settings === 'object' && result.settings ? result.settings as Settings : null;
      setState({ loading: false, error: null, message: 'Document company settings saved. / 公司文档设置已保存。', settings, result });
    } catch (error) {
      setState((current) => ({ ...current, loading: false, error: error instanceof Error ? error.message : String(error), result: null }));
    }
  }

  useEffect(() => { void refresh(); }, []);

  return (
    <section className="overflow-hidden rounded-3xl bg-white shadow-soft ring-1 ring-slate-200">
      <div className="bg-slate-50 px-6 py-5">
        <div className="text-xs font-black uppercase tracking-[0.18em] text-activeBlue">Document Company Settings / 公司文档设置</div>
        <h2 className="mt-2 text-xl font-black text-slate-950">Invoice / Quotation PDF Template Settings</h2>
        <p className="mt-2 text-sm font-semibold text-slate-600">These settings drive the polished invoice PDF template and can be reused later for quotation PDFs. / 这些设置用于美化发票 PDF 模板，后续也可复用到报价 PDF。</p>
      </div>
      <form onSubmit={(event) => void submit(event)} className="grid gap-5 p-6">
        {state.error ? <div className="rounded-2xl bg-red-50 p-4 text-xs font-bold text-red-950 ring-1 ring-red-200">{state.error}</div> : null}
        {state.message ? <div className="rounded-2xl bg-emerald-50 p-4 text-xs font-bold text-emerald-950 ring-1 ring-emerald-200">{state.message}</div> : null}
        <div className="grid gap-4 md:grid-cols-2">
          <Field label="Company Name / 公司名称" value={values.company_name} onChange={(value) => change('company_name', value)} />
          <Field label="Company Tagline / 公司标语" value={values.company_tagline} onChange={(value) => change('company_tagline', value)} />
          <Field label="UEN" value={values.uen} onChange={(value) => change('uen', value)} />
          <Field label="GST Registration No" value={values.gst_registration_no} onChange={(value) => change('gst_registration_no', value)} />
          <Field label="Address Line 1 / 地址1" value={values.address_line_1} onChange={(value) => change('address_line_1', value)} />
          <Field label="Address Line 2 / 地址2" value={values.address_line_2} onChange={(value) => change('address_line_2', value)} />
          <Field label="Phone / 电话" value={values.phone} onChange={(value) => change('phone', value)} />
          <Field label="WhatsApp" value={values.whatsapp} onChange={(value) => change('whatsapp', value)} />
          <Field label="Email / 邮箱" value={values.email} onChange={(value) => change('email', value)} />
          <Field label="Website / 网站" value={values.website} onChange={(value) => change('website', value)} />
          <Field label="Logo Storage Path / LOGO 存储路径" value={values.logo_storage_path} onChange={(value) => change('logo_storage_path', value)} />
          <Field label="Invoice Prefix / 发票前缀" value={values.invoice_prefix} onChange={(value) => change('invoice_prefix', value)} />
          <Field label="Quotation Prefix / 报价前缀" value={values.quotation_prefix} onChange={(value) => change('quotation_prefix', value)} />
          <Field label="Primary Color / 主色" value={values.primary_color} onChange={(value) => change('primary_color', value)} />
          <Field label="Secondary Color / 辅色" value={values.secondary_color} onChange={(value) => change('secondary_color', value)} />
          <Area label="Payment Instructions / 付款说明" value={values.payment_instructions} onChange={(value) => change('payment_instructions', value)} />
          <Area label="Warranty Footer / 保修页脚" value={values.warranty_footer} onChange={(value) => change('warranty_footer', value)} />
          <Area label="Terms Footer / 条款页脚" value={values.terms_footer} onChange={(value) => change('terms_footer', value)} />
        </div>
        <div className="flex flex-wrap gap-2">
          <button type="submit" disabled={state.loading} className="rounded-2xl bg-activeBlue px-5 py-3 text-sm font-black text-white hover:bg-blue-700 disabled:opacity-50">Save Document Settings / 保存文档设置</button>
          <button type="button" onClick={() => void refresh()} disabled={state.loading} className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-activeBlue ring-1 ring-blue-100 hover:bg-blue-50 disabled:opacity-50">Reload / 重新读取</button>
        </div>
        {state.result ? <pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-xs font-semibold text-slate-700 ring-1 ring-slate-200">{JSON.stringify(state.result, null, 2)}</pre> : null}
      </form>
    </section>
  );
}
