import { z } from "zod";
import { insertIfConfigured } from "@/lib/supabase-server";
import { ok, validationError } from "@/lib/nanofix/api";
import { requireAdmin } from "@/lib/nanofix/auth";

export const dynamic = "force-dynamic";

const DraftSchema = z.object({
  module: z.string().trim().min(1).max(80),
  record_id: z.string().trim().max(120).optional(),
  task: z.string().trim().min(1).max(120),
  input: z.string().trim().min(1).max(8000),
  risk_level: z.enum(["low", "medium", "high", "critical"]).default("medium")
});

export async function POST(request: Request) {
  const { context, response } = requireAdmin(request, "write:ai");
  if (response) return response;

  const parsed = DraftSchema.safeParse(await request.json());
  if (!parsed.success) {
    return validationError(parsed.error);
  }

  const requiresReview = parsed.data.risk_level !== "low";
  const generatedOutput =
    "Draft generated by NANOFIX AI contract. Connect an approved provider server-side to replace this placeholder. Human review is required before any customer-facing action.";

  const inserted = await insertIfConfigured("ai_drafts", {
    module: parsed.data.module,
    record_id: parsed.data.record_id ?? null,
    task: parsed.data.task,
    input_text: parsed.data.input,
    output_text: generatedOutput,
    ai_confidence: 0.72,
    ai_risk_level: parsed.data.risk_level,
    human_review_status: requiresReview ? "pending_review" : "auto_internal",
    created_by: context?.actorId ?? null,
    created_at: new Date().toISOString()
  });

  if (inserted.skipped) return ok({ ok: false, error: "Supabase is not configured for AI draft writes" }, { status: 503 });
  if (inserted.error) return ok({ ok: false, error: "AI draft storage failed" }, { status: 500 });

  return ok({
    draft_id: inserted.data?.draft_id ?? null,
    risk_level: parsed.data.risk_level,
    confidence: 0.72,
    status: requiresReview ? "pending_review" : "auto_internal",
    output: generatedOutput,
    storage: "supabase"
  });
}
