export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { cleanText, getClientIp, jsonError, requireActorApi } from '@/lib/apiSecurity';
import { createAdminClient } from '@/lib/supabase/admin';
import { writeAuditLog } from '@/lib/audit';

const READ_ROLES = ['super_admin', 'operations_admin', 'finance', 'support'] as const;
const WRITE_ROLES = ['super_admin', 'operations_admin', 'finance'] as const;
const BUCKET = 'service-uploads';
type ApiPayload = Record<string, unknown>;
type Quotation = Record<string, unknown>;
type QuotationVersion = Record<string, unknown>;
type CompanySettings = Record<string, unknown>;

type LineItem = { description?: string; qty?: number; unit_price?: number; amount?: number };

function isUuid(value: string | null | undefined) {
  return Boolean(value && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value));
}

function pdfEscape(value: unknown) {
  return String(value ?? '').replace(/[\\()]/g, (match) => `\\${match}`).slice(0, 180);
}

function formatMoney(value: unknown) {
  const number = Number(value ?? 0);
  return Number.isFinite(number) ? number.toFixed(2) : '0.00';
}

function safePath(value: string) {
  return value.replace(/[^a-z0-9_.-]/gi, '-').replace(/-+/g, '-').slice(0, 120) || 'quotation';
}

function settingText(settings: CompanySettings, key: string, fallback = '') {
  const value = settings[key];
  return typeof value === 'string' && value.trim() ? value.trim() : fallback;
}

function lineItems(version: QuotationVersion | null): LineItem[] {
  const raw = version?.line_items;
  return Array.isArray(raw) ? raw.filter((item): item is LineItem => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : [];
}

function buildQuotationPdf(quotation: Quotation, version: QuotationVersion | null, settings: CompanySettings) {
  const companyName = settingText(settings, 'company_name', 'NANOFIX');
  const tagline = settingText(settings, 'company_tagline', 'No-Hacking Leak Repair & Waterproofing Solutions');
  const uen = settingText(settings, 'uen');
  const gst = settingText(settings, 'gst_registration_no');
  const address1 = settingText(settings, 'address_line_1');
  const address2 = settingText(settings, 'address_line_2');
  const phone = settingText(settings, 'phone', '+65 8038 7877');
  const whatsapp = settingText(settings, 'whatsapp', '+65 8038 7877');
  const email = settingText(settings, 'email');
  const website = settingText(settings, 'website', 'https://www.nanofixsg.com');
  const warrantyFooter = settingText(settings, 'warranty_footer', 'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.');
  const termsFooter = settingText(settings, 'terms_footer', 'This quotation is system-generated by NANOFIX Service Operations.');
  const quotationNo = pdfEscape(quotation.public_ref || quotation.quotation_id || 'Quotation');
  const total = formatMoney(version?.total ?? quotation.total);
  const items = lineItems(version);
  const lines = [
    companyName.toUpperCase(),
    tagline,
    uen ? `UEN: ${uen}` : '',
    gst ? `GST Reg No: ${gst}` : '',
    address1,
    address2,
    `Phone: ${phone}    WhatsApp: ${whatsapp}`,
    email ? `Email: ${email}` : '',
    `Website: ${website}`,
    '',
    'QUOTATION',
    `Quotation Ref: ${quotationNo}`,
    `Quotation ID: ${pdfEscape(quotation.quotation_id)}`,
    `Job ID: ${pdfEscape(quotation.job_id)}`,
    `Version: ${pdfEscape(version?.version ?? quotation.current_version ?? '-')}`,
    `Approval Status: ${pdfEscape(quotation.approval_status)}`,
    `Created: ${pdfEscape(quotation.created_at)}`,
    '',
    'Scope / Quotation Items:',
    'Description                                      Qty       Unit       Amount'
  ].filter(Boolean);
  items.slice(0, 20).forEach((item, index) => {
    const description = pdfEscape(item.description).padEnd(44, ' ').slice(0, 44);
    lines.push(`${String(index + 1).padStart(2, '0')}. ${description} ${formatMoney(item.qty).padStart(7, ' ')} ${formatMoney(item.unit_price).padStart(10, ' ')} ${formatMoney(item.amount).padStart(11, ' ')}`);
  });
  lines.push('', `Quoted Total SGD: ${total}`, '', 'Acceptance:', 'Customer may accept this quotation through NANOFIX Customer Portal if it is visible to customer.', '', 'Warranty / Service Terms:', warrantyFooter, '', 'Terms:', termsFooter);

  const textOps = lines.slice(0, 42).map((line, index) => `BT /F1 ${index === 0 ? 15 : index === 10 ? 13 : 9} Tf 45 ${795 - index * 17} Td (${pdfEscape(line)}) Tj ET`).join('\n');
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(textOps)} >> stream\n${textOps}\nendstream endobj`
  ];
  let body = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(body));
    body += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { body += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  body += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(body, 'utf8');
}

async function loadDocumentSettings() {
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('document_company_settings')
    .select('setting_id,setting_key,company_name,company_tagline,uen,gst_registration_no,address_line_1,address_line_2,phone,whatsapp,email,website,logo_storage_path,invoice_prefix,quotation_prefix,payment_instructions,warranty_footer,terms_footer,primary_color,secondary_color,is_active,updated_at')
    .eq('setting_key', 'nanofix_default')
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data ?? { company_name: 'NANOFIX', company_tagline: 'No-Hacking Leak Repair & Waterproofing Solutions', phone: '+65 8038 7877', whatsapp: '+65 8038 7877', website: 'https://www.nanofixsg.com' };
}

async function loadQuotation(quotationId: string) {
  const supabase = createAdminClient();
  const { data: quotation, error: quotationError } = await supabase
    .from('quotations')
    .select('quotation_id,job_id,current_version,total,approval_status,visible_to_customer,customer_visibility_notes,pdf_storage_path,public_ref,created_at')
    .eq('quotation_id', quotationId)
    .maybeSingle();
  if (quotationError) throw new Error(quotationError.message);
  if (!quotation) throw new Error('Quotation not found.');

  const { data: version, error: versionError } = await supabase
    .from('quotation_versions')
    .select('version_id,quotation_id,version,line_items,total,created_by,approval_log,created_at')
    .eq('quotation_id', quotationId)
    .order('version', { ascending: false })
    .limit(1)
    .maybeSingle();
  if (versionError) throw new Error(versionError.message);
  return { quotation, version };
}

async function customerForJob(jobId: unknown) {
  const supabase = createAdminClient();
  if (!jobId || typeof jobId !== 'string') return null;
  const { data } = await supabase.from('jobs').select('customer_id').eq('job_id', jobId).maybeSingle();
  return data?.customer_id ?? null;
}

export async function GET(request: NextRequest) {
  const auth = await requireActorApi(request, [...READ_ROLES]);
  if (!auth.ok) return auth.response;
  const quotationId = cleanText(request.nextUrl.searchParams.get('quotation_id'), 120);
  if (!isUuid(quotationId)) return jsonError('Valid quotation_id is required.', 400);
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('quotation_pdf_documents')
    .select('quotation_pdf_id,quotation_id,job_id,customer_id,quotation_version,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,generation_notes,created_at')
    .eq('quotation_id', quotationId)
    .order('created_at', { ascending: false })
    .limit(20);
  if (error) return jsonError(error.message, 500);
  await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_quotation_pdfs_read', objectType: 'quotation', objectId: quotationId, after: { count: data?.length ?? 0 }, ip: getClientIp(request) }).catch(() => undefined);
  return NextResponse.json({ ok: true, quotation_pdfs: data ?? [] });
}

export async function POST(request: NextRequest) {
  const auth = await requireActorApi(request, [...WRITE_ROLES]);
  if (!auth.ok) return auth.response;
  const body = await request.json().catch(() => ({})) as ApiPayload;
  const action = cleanText(body.action, 100);
  const quotationId = cleanText(body.quotation_id, 120);
  if (action !== 'generate_quotation_pdf') return jsonError('Unsupported quotation PDF action.', 400);
  if (!isUuid(quotationId)) return jsonError('Valid quotation_id is required.', 400);

  const visibleToCustomer = body.visible_to_customer === true;
  const notes = cleanText(body.generation_notes, 1000) || 'Quotation PDF generated from Service Operations.';
  const supabase = createAdminClient();

  try {
    const { quotation, version } = await loadQuotation(quotationId);
    const settings = await loadDocumentSettings();
    const pdf = buildQuotationPdf(quotation, version, settings);
    const quotationRef = safePath(String(quotation.public_ref || quotation.quotation_id));
    const storagePath = `service-operations/quotations/${safePath(quotationId)}/${Date.now()}-${quotationRef}.pdf`;
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(storagePath, pdf, { contentType: 'application/pdf', upsert: false });
    if (uploadError) throw new Error(uploadError.message);

    const customerId = await customerForJob(quotation.job_id);
    const { data: doc, error: docError } = await supabase
      .from('quotation_pdf_documents')
      .insert({
        quotation_id: quotationId,
        job_id: typeof quotation.job_id === 'string' ? quotation.job_id : null,
        customer_id: customerId,
        quotation_version: Number(version?.version ?? quotation.current_version ?? 0) || null,
        storage_bucket: BUCKET,
        storage_path: storagePath,
        file_name: `${quotationRef}.pdf`,
        file_size_bytes: pdf.byteLength,
        generation_status: 'uploaded',
        visible_to_customer: visibleToCustomer,
        generated_by: auth.actor.profileId,
        generation_notes: notes,
        metadata_json: { quotation_ref: quotation.public_ref, total: version?.total ?? quotation.total, version: version?.version ?? quotation.current_version, company_setting_id: settings.setting_id ?? null, template: 'nanofix_quotation_polished_v1' }
      })
      .select('quotation_pdf_id,quotation_id,job_id,customer_id,quotation_version,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,created_at')
      .single();
    if (docError) throw new Error(docError.message);

    const { data: updatedQuotation, error: quotationError } = await supabase
      .from('quotations')
      .update({
        pdf_storage_path: storagePath,
        visible_to_customer: visibleToCustomer,
        customer_visible_at: visibleToCustomer ? new Date().toISOString() : null,
        customer_visible_by: visibleToCustomer ? auth.actor.profileId : null
      })
      .eq('quotation_id', quotationId)
      .select('quotation_id,job_id,current_version,total,approval_status,visible_to_customer,pdf_storage_path,customer_visible_at,customer_visible_by,public_ref,created_at')
      .single();
    if (quotationError) throw new Error(quotationError.message);

    const { data: task, error: taskError } = await supabase.from('unified_tasks').insert({
      source_module: 'service_operations',
      source_table: 'quotation_pdf_documents',
      source_id: doc.quotation_pdf_id,
      title: 'Quotation PDF generated',
      description: `Quotation PDF generated for quotation ${quotationId}.`,
      priority: 'P2',
      assignee_role: 'finance',
      status: 'open',
      metadata_json: { quotation_id: quotationId, storage_path: storagePath, template: 'nanofix_quotation_polished_v1' }
    }).select('task_id,source_module,source_table,source_id,title,status,priority,assignee_role,created_at').single();
    if (taskError) throw new Error(taskError.message);
    await supabase.from('task_events').insert({ task_id: task.task_id, action: 'quotation_pdf_generated', after_json: { quotation_pdf: doc, quotation: updatedQuotation, template: 'nanofix_quotation_polished_v1' } }).throwOnError();
    await supabase.from('internal_inbox_messages').insert({
      recipient_role: 'finance',
      subject: 'Quotation PDF generated',
      body: `Quotation PDF generated for quotation ${quotationId}.`,
      category: 'quotation_pdf',
      priority: 'P2',
      related_object_type: 'quotation_pdf_document',
      related_object_id: doc.quotation_pdf_id,
      task_id: task.task_id
    }).throwOnError();

    if (visibleToCustomer && customerId) {
      await supabase.from('notification_outbox').insert({
        channel: 'internal',
        recipient_customer_id: customerId,
        subject: 'NANOFIX quotation PDF is ready',
        body: 'Your NANOFIX quotation PDF is ready in Customer Portal.',
        payload_json: { source: 'quotation_pdf_generator', quotation_id: quotationId, storage_path: storagePath, template: 'nanofix_quotation_polished_v1' },
        delivery_status: 'queued',
        related_object_type: 'quotation',
        related_object_id: quotationId
      }).throwOnError();
    }

    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_quotation_pdf_generate', objectType: 'quotation', objectId: quotationId, after: { quotation_pdf: doc, quotation: updatedQuotation, task, company_settings: settings.setting_id ?? null }, ip: getClientIp(request) }).catch(() => undefined);
    return NextResponse.json({ ok: true, quotation_pdf: doc, quotation: updatedQuotation, task }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_quotation_pdf_generate_failed', objectType: 'quotation', objectId: quotationId, after: { error: message }, ip: getClientIp(request) }).catch(() => undefined);
    return jsonError(message, 500);
  }
}
