export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { cleanText, getClientIp, jsonError, requireActorApi } from '@/lib/apiSecurity';
import { createAdminClient } from '@/lib/supabase/admin';
import { writeAuditLog } from '@/lib/audit';

const READ_ROLES = ['super_admin', 'operations_admin', 'finance', 'support'] as const;
const WRITE_ROLES = ['super_admin', 'operations_admin', 'finance'] as const;
const BUCKET = 'service-uploads';
type ApiPayload = Record<string, unknown>;
type Invoice = Record<string, unknown>;
type InvoiceItem = Record<string, unknown>;
type CompanySettings = Record<string, unknown>;

function isUuid(value: string | null | undefined) {
  return Boolean(value && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value));
}

function pdfEscape(value: unknown) {
  return String(value ?? '').replace(/[\\()]/g, (match) => `\\${match}`).slice(0, 180);
}

function formatMoney(value: unknown) {
  const number = Number(value ?? 0);
  return Number.isFinite(number) ? number.toFixed(2) : '0.00';
}

function safePath(value: string) {
  return value.replace(/[^a-z0-9_.-]/gi, '-').replace(/-+/g, '-').slice(0, 120) || 'invoice';
}

function settingText(settings: CompanySettings, key: string, fallback = '') {
  const value = settings[key];
  return typeof value === 'string' && value.trim() ? value.trim() : fallback;
}

function buildInvoicePdf(invoice: Invoice, items: InvoiceItem[], settings: CompanySettings) {
  const companyName = settingText(settings, 'company_name', 'NANOFIX');
  const tagline = settingText(settings, 'company_tagline', 'No-Hacking Leak Repair & Waterproofing Solutions');
  const uen = settingText(settings, 'uen');
  const gst = settingText(settings, 'gst_registration_no');
  const address1 = settingText(settings, 'address_line_1');
  const address2 = settingText(settings, 'address_line_2');
  const phone = settingText(settings, 'phone', '+65 8038 7877');
  const whatsapp = settingText(settings, 'whatsapp', '+65 8038 7877');
  const email = settingText(settings, 'email');
  const website = settingText(settings, 'website', 'https://www.nanofixsg.com');
  const paymentInstructions = settingText(settings, 'payment_instructions', 'Please make payment using the payment link provided in Customer Portal.');
  const warrantyFooter = settingText(settings, 'warranty_footer', 'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.');
  const termsFooter = settingText(settings, 'terms_footer', 'This document is system-generated by NANOFIX Service Operations.');
  const invoiceNo = pdfEscape(invoice.invoice_no || invoice.invoice_id || 'Invoice');
  const total = formatMoney(invoice.total);
  const lines = [
    companyName.toUpperCase(),
    tagline,
    uen ? `UEN: ${uen}` : '',
    gst ? `GST Reg No: ${gst}` : '',
    address1,
    address2,
    `Phone: ${phone}    WhatsApp: ${whatsapp}`,
    email ? `Email: ${email}` : '',
    `Website: ${website}`,
    '',
    'TAX INVOICE / INVOICE',
    `Invoice No: ${invoiceNo}`,
    `Invoice ID: ${pdfEscape(invoice.invoice_id)}`,
    `Job ID: ${pdfEscape(invoice.job_id)}`,
    `Status: ${pdfEscape(invoice.status)}`,
    `Created: ${pdfEscape(invoice.created_at)}`,
    '',
    'Invoice Items:',
    'Description                                      Qty       Unit       Amount'
  ].filter(Boolean);
  items.slice(0, 20).forEach((item, index) => {
    const description = pdfEscape(item.description).padEnd(44, ' ').slice(0, 44);
    lines.push(`${String(index + 1).padStart(2, '0')}. ${description} ${formatMoney(item.qty).padStart(7, ' ')} ${formatMoney(item.unit_price).padStart(10, ' ')} ${formatMoney(item.amount).padStart(11, ' ')}`);
  });
  lines.push('', `Total Payable SGD: ${total}`, '', 'Payment Instructions:', paymentInstructions, '', 'Warranty / Service Terms:', warrantyFooter, '', 'Terms:', termsFooter);

  const textOps = lines.slice(0, 42).map((line, index) => `BT /F1 ${index === 0 ? 15 : index === 10 ? 13 : 9} Tf 45 ${795 - index * 17} Td (${pdfEscape(line)}) Tj ET`).join('\n');
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(textOps)} >> stream\n${textOps}\nendstream endobj`
  ];
  let body = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(body));
    body += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { body += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  body += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(body, 'utf8');
}

async function loadInvoice(invoiceId: string) {
  const supabase = createAdminClient();
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .select('invoice_id,invoice_no,job_id,total,status,visible_to_customer,pdf_storage_path,payment_url,public_ref,created_at')
    .eq('invoice_id', invoiceId)
    .maybeSingle();
  if (invoiceError) throw new Error(invoiceError.message);
  if (!invoice) throw new Error('Invoice not found.');

  const { data: items, error: itemError } = await supabase
    .from('invoice_items')
    .select('invoice_item_id,invoice_id,description,qty,unit_price,amount,created_at')
    .eq('invoice_id', invoiceId)
    .order('created_at', { ascending: true });
  if (itemError) throw new Error(itemError.message);
  return { invoice, items: items ?? [] };
}

async function loadDocumentSettings() {
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('document_company_settings')
    .select('setting_id,setting_key,company_name,company_tagline,uen,gst_registration_no,address_line_1,address_line_2,phone,whatsapp,email,website,logo_storage_path,invoice_prefix,quotation_prefix,payment_instructions,warranty_footer,terms_footer,primary_color,secondary_color,is_active,updated_at')
    .eq('setting_key', 'nanofix_default')
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data ?? { company_name: 'NANOFIX', company_tagline: 'No-Hacking Leak Repair & Waterproofing Solutions', phone: '+65 8038 7877', whatsapp: '+65 8038 7877', website: 'https://www.nanofixsg.com' };
}

async function customerForJob(jobId: unknown) {
  const supabase = createAdminClient();
  if (!jobId || typeof jobId !== 'string') return null;
  const { data } = await supabase.from('jobs').select('customer_id').eq('job_id', jobId).maybeSingle();
  return data?.customer_id ?? null;
}

export async function GET(request: NextRequest) {
  const auth = await requireActorApi(request, [...READ_ROLES]);
  if (!auth.ok) return auth.response;
  const invoiceId = cleanText(request.nextUrl.searchParams.get('invoice_id'), 120);
  if (!isUuid(invoiceId)) return jsonError('Valid invoice_id is required.', 400);
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('invoice_pdf_documents')
    .select('invoice_pdf_id,invoice_id,job_id,customer_id,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,generation_notes,created_at')
    .eq('invoice_id', invoiceId)
    .order('created_at', { ascending: false })
    .limit(20);
  if (error) return jsonError(error.message, 500);
  await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_invoice_pdfs_read', objectType: 'invoice', objectId: invoiceId, after: { count: data?.length ?? 0 }, ip: getClientIp(request) }).catch(() => undefined);
  return NextResponse.json({ ok: true, invoice_pdfs: data ?? [] });
}

export async function POST(request: NextRequest) {
  const auth = await requireActorApi(request, [...WRITE_ROLES]);
  if (!auth.ok) return auth.response;
  const body = await request.json().catch(() => ({})) as ApiPayload;
  const action = cleanText(body.action, 100);
  const invoiceId = cleanText(body.invoice_id, 120);
  if (action !== 'generate_invoice_pdf') return jsonError('Unsupported invoice PDF action.', 400);
  if (!isUuid(invoiceId)) return jsonError('Valid invoice_id is required.', 400);

  const visibleToCustomer = body.visible_to_customer === true;
  const notes = cleanText(body.generation_notes, 1000) || 'Invoice PDF generated from Service Operations.';
  const supabase = createAdminClient();

  try {
    const { invoice, items } = await loadInvoice(invoiceId);
    const settings = await loadDocumentSettings();
    const pdf = buildInvoicePdf(invoice, items, settings);
    const invoiceNo = safePath(String(invoice.invoice_no || invoice.invoice_id));
    const storagePath = `service-operations/invoices/${safePath(invoiceId)}/${Date.now()}-${invoiceNo}.pdf`;
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(storagePath, pdf, { contentType: 'application/pdf', upsert: false });
    if (uploadError) throw new Error(uploadError.message);

    const customerId = await customerForJob(invoice.job_id);
    const { data: doc, error: docError } = await supabase
      .from('invoice_pdf_documents')
      .insert({
        invoice_id: invoiceId,
        job_id: typeof invoice.job_id === 'string' ? invoice.job_id : null,
        customer_id: customerId,
        storage_bucket: BUCKET,
        storage_path: storagePath,
        file_name: `${invoiceNo}.pdf`,
        file_size_bytes: pdf.byteLength,
        generation_status: 'uploaded',
        visible_to_customer: visibleToCustomer,
        generated_by: auth.actor.profileId,
        generation_notes: notes,
        metadata_json: { invoice_no: invoice.invoice_no, total: invoice.total, item_count: items.length, company_setting_id: settings.setting_id ?? null, template: 'nanofix_polished_v1' }
      })
      .select('invoice_pdf_id,invoice_id,job_id,customer_id,storage_bucket,storage_path,file_name,file_size_bytes,generation_status,visible_to_customer,created_at')
      .single();
    if (docError) throw new Error(docError.message);

    const { data: updatedInvoice, error: invoiceError } = await supabase
      .from('invoices')
      .update({
        pdf_storage_path: storagePath,
        visible_to_customer: visibleToCustomer,
        customer_visible_at: visibleToCustomer ? new Date().toISOString() : null,
        customer_visible_by: visibleToCustomer ? auth.actor.profileId : null
      })
      .eq('invoice_id', invoiceId)
      .select('invoice_id,invoice_no,job_id,total,status,visible_to_customer,pdf_storage_path,customer_visible_at,customer_visible_by,created_at')
      .single();
    if (invoiceError) throw new Error(invoiceError.message);

    const { data: task, error: taskError } = await supabase.from('unified_tasks').insert({
      source_module: 'service_operations',
      source_table: 'invoice_pdf_documents',
      source_id: doc.invoice_pdf_id,
      title: 'Invoice PDF generated',
      description: `Polished invoice PDF generated for invoice ${invoiceId}.`,
      priority: 'P2',
      assignee_role: 'finance',
      status: 'open',
      metadata_json: { invoice_id: invoiceId, storage_path: storagePath, template: 'nanofix_polished_v1' }
    }).select('task_id,source_module,source_table,source_id,title,status,priority,assignee_role,created_at').single();
    if (taskError) throw new Error(taskError.message);
    await supabase.from('task_events').insert({ task_id: task.task_id, action: 'invoice_pdf_generated', after_json: { invoice_pdf: doc, invoice: updatedInvoice, template: 'nanofix_polished_v1' } }).throwOnError();
    await supabase.from('internal_inbox_messages').insert({
      recipient_role: 'finance',
      subject: 'Invoice PDF generated',
      body: `Polished invoice PDF generated for invoice ${invoiceId}.`,
      category: 'invoice_pdf',
      priority: 'P2',
      related_object_type: 'invoice_pdf_document',
      related_object_id: doc.invoice_pdf_id,
      task_id: task.task_id
    }).throwOnError();

    if (visibleToCustomer && customerId) {
      await supabase.from('notification_outbox').insert({
        channel: 'internal',
        recipient_customer_id: customerId,
        subject: 'NANOFIX invoice PDF is ready',
        body: 'Your NANOFIX invoice PDF is ready in Customer Portal.',
        payload_json: { source: 'invoice_pdf_generator', invoice_id: invoiceId, storage_path: storagePath, template: 'nanofix_polished_v1' },
        delivery_status: 'queued',
        related_object_type: 'invoice',
        related_object_id: invoiceId
      }).throwOnError();
    }

    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_invoice_pdf_generate', objectType: 'invoice', objectId: invoiceId, after: { invoice_pdf: doc, invoice: updatedInvoice, task, company_settings: settings.setting_id ?? null }, ip: getClientIp(request) }).catch(() => undefined);
    return NextResponse.json({ ok: true, invoice_pdf: doc, invoice: updatedInvoice, task }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await writeAuditLog({ actorId: auth.actor.profileId, role: auth.role, action: 'service_operations_invoice_pdf_generate_failed', objectType: 'invoice', objectId: invoiceId, after: { error: message }, ip: getClientIp(request) }).catch(() => undefined);
    return jsonError(message, 500);
  }
}
