-- NANOFIX V28.2 Phase D.3
-- Warranty PDF documents generated by Internal Admin and downloadable by the linked customer.

create table if not exists public.warranty_pdf_documents (
  warranty_pdf_id uuid primary key default gen_random_uuid(),
  warranty_id uuid not null references public.warranties(warranty_id) on delete cascade,
  customer_id uuid references public.customers(customer_id) on delete set null,
  job_id uuid references public.jobs(job_id) on delete set null,
  warranty_version integer not null default 1,
  storage_bucket text not null default 'service-uploads',
  storage_path text not null,
  file_name text not null,
  mime_type text not null default 'application/pdf',
  file_size_bytes bigint not null default 0,
  checksum_sha256 text,
  public_ref text,
  generation_status text not null default 'generated' check (generation_status in ('queued','generated','uploaded','failed','superseded','revoked')),
  visible_to_customer boolean not null default false,
  customer_visible_at timestamptz,
  customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  generated_by uuid references public.profiles(profile_id) on delete set null,
  generated_at timestamptz not null default now(),
  generation_notes text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(warranty_id, warranty_version)
);

alter table public.warranty_pdf_documents
  add column if not exists warranty_version integer not null default 1,
  add column if not exists mime_type text not null default 'application/pdf',
  add column if not exists checksum_sha256 text,
  add column if not exists public_ref text,
  add column if not exists customer_visible_at timestamptz,
  add column if not exists customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  add column if not exists generated_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists warranty_pdf_documents_warranty_idx on public.warranty_pdf_documents(warranty_id, warranty_version desc, created_at desc);
create index if not exists warranty_pdf_documents_customer_idx on public.warranty_pdf_documents(customer_id, visible_to_customer, created_at desc);
create index if not exists warranty_pdf_documents_job_idx on public.warranty_pdf_documents(job_id, created_at desc);
create index if not exists warranty_pdf_documents_status_idx on public.warranty_pdf_documents(generation_status, created_at desc);

create or replace function public.warranty_pdf_documents_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists warranty_pdf_documents_touch_updated_at on public.warranty_pdf_documents;
create trigger warranty_pdf_documents_touch_updated_at
before update on public.warranty_pdf_documents
for each row execute function public.warranty_pdf_documents_touch_updated_at();

alter table public.warranty_pdf_documents enable row level security;

drop policy if exists "customers can read own visible warranty pdfs" on public.warranty_pdf_documents;
create policy "customers can read own visible warranty pdfs"
on public.warranty_pdf_documents for select
using (visible_to_customer = true and public.owns_customer(customer_id));

drop policy if exists "internal roles can read warranty pdfs" on public.warranty_pdf_documents;
create policy "internal roles can read warranty pdfs"
on public.warranty_pdf_documents for select
using (public.current_profile_role() in ('super_admin','operations_admin','finance','support'));

drop policy if exists "service role can manage warranty pdfs" on public.warranty_pdf_documents;
create policy "service role can manage warranty pdfs"
on public.warranty_pdf_documents for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

alter table public.warranties
  add column if not exists pdf_storage_path text,
  add column if not exists visible_to_customer boolean not null default false,
  add column if not exists customer_visible_at timestamptz,
  add column if not exists customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  add column if not exists customer_visibility_notes text;

create index if not exists warranties_customer_visible_idx on public.warranties(customer_id, visible_to_customer, created_at desc);
