-- NANOFIX V28.2 Service Operations Phase C.7
-- Company document settings for polished invoice / quotation PDF templates.

create table if not exists public.document_company_settings (
  setting_id uuid primary key default gen_random_uuid(),
  setting_key text not null unique default 'nanofix_default',
  company_name text not null default 'NANOFIX',
  company_tagline text default 'No-Hacking Leak Repair & Waterproofing Solutions',
  uen text,
  gst_registration_no text,
  address_line_1 text,
  address_line_2 text,
  phone text default '+65 8038 7877',
  whatsapp text default '+65 8038 7877',
  email text,
  website text default 'https://www.nanofixsg.com',
  logo_storage_path text,
  invoice_prefix text default 'NFX-INV',
  quotation_prefix text default 'NFX-QUO',
  payment_instructions text default 'Please make payment using the payment link provided in Customer Portal or contact NANOFIX for bank transfer instructions.',
  warranty_footer text default 'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.',
  terms_footer text default 'This document is system-generated by NANOFIX Service Operations. All prices are in SGD unless otherwise stated.',
  primary_color text default '#FF5F00',
  secondary_color text default '#1E293B',
  is_active boolean not null default true,
  updated_by uuid references public.profiles(profile_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.document_company_settings (
  setting_key,
  company_name,
  company_tagline,
  phone,
  whatsapp,
  website,
  payment_instructions,
  warranty_footer,
  terms_footer,
  is_active
) values (
  'nanofix_default',
  'NANOFIX',
  'No-Hacking Leak Repair & Waterproofing Solutions',
  '+65 8038 7877',
  '+65 8038 7877',
  'https://www.nanofixsg.com',
  'Please make payment using the payment link provided in Customer Portal or contact NANOFIX for bank transfer instructions.',
  'Warranty coverage is subject to NANOFIX warranty terms and the approved scope of work.',
  'This document is system-generated by NANOFIX Service Operations. All prices are in SGD unless otherwise stated.',
  true
) on conflict (setting_key) do nothing;

create index if not exists document_company_settings_active_idx on public.document_company_settings(is_active, updated_at desc);

create or replace function public.document_company_settings_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists document_company_settings_touch_updated_at on public.document_company_settings;
create trigger document_company_settings_touch_updated_at
before update on public.document_company_settings
for each row execute function public.document_company_settings_touch_updated_at();

alter table public.document_company_settings enable row level security;

drop policy if exists "internal roles can read document company settings" on public.document_company_settings;
create policy "internal roles can read document company settings"
on public.document_company_settings for select
using (public.current_profile_role() in ('super_admin','operations_admin','finance','support'));

drop policy if exists "service role can write document company settings" on public.document_company_settings;
create policy "service role can write document company settings"
on public.document_company_settings for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
