-- NANOFIX V28.2 Phase D.3
-- Warranty PDF generator + Customer Portal warranty download.
-- The official warranty document can be generated/regenerated by Internal Admin.
-- Customer Portal can only read/download warranties linked to the logged-in customer.

alter table public.warranties
  add column if not exists pdf_storage_path text,
  add column if not exists pdf_generated_at timestamptz,
  add column if not exists pdf_generated_by uuid references public.profiles(profile_id) on delete set null,
  add column if not exists visible_to_customer boolean not null default false,
  add column if not exists customer_visible_at timestamptz,
  add column if not exists customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  add column if not exists customer_visibility_notes text,
  add column if not exists public_ref text;

create table if not exists public.warranty_pdf_documents (
  warranty_pdf_id uuid primary key default gen_random_uuid(),
  warranty_id uuid not null references public.warranties(warranty_id) on delete cascade,
  job_id uuid references public.jobs(job_id) on delete set null,
  customer_id uuid references public.customers(customer_id) on delete set null,
  warranty_version integer not null default 1,
  storage_bucket text not null default 'service-uploads',
  storage_path text not null,
  file_name text not null default 'warranty.pdf',
  mime_type text not null default 'application/pdf',
  file_size_bytes bigint,
  public_ref text,
  generation_status text not null default 'uploaded' check (generation_status in ('queued','generated','uploaded','failed')),
  visible_to_customer boolean not null default false,
  customer_visible_at timestamptz,
  customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  generated_by uuid references public.profiles(profile_id) on delete set null,
  generated_at timestamptz not null default now(),
  generation_notes text,
  template_key text not null default 'nanofix_standard_warranty',
  document_snapshot jsonb not null default '{}'::jsonb,
  metadata_json jsonb not null default '{}'::jsonb,
  superseded_by uuid references public.warranty_pdf_documents(warranty_pdf_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.warranty_pdf_documents
  add column if not exists storage_bucket text not null default 'service-uploads',
  add column if not exists file_name text not null default 'warranty.pdf',
  add column if not exists mime_type text not null default 'application/pdf',
  add column if not exists file_size_bytes bigint,
  add column if not exists generation_status text not null default 'uploaded',
  add column if not exists customer_visible_at timestamptz,
  add column if not exists customer_visible_by uuid references public.profiles(profile_id) on delete set null,
  add column if not exists generation_notes text,
  add column if not exists metadata_json jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists warranty_pdf_documents_version_uq on public.warranty_pdf_documents(warranty_id, warranty_version);
create index if not exists warranty_pdf_documents_warranty_idx on public.warranty_pdf_documents(warranty_id, generated_at desc);
create index if not exists warranty_pdf_documents_customer_idx on public.warranty_pdf_documents(customer_id, visible_to_customer, generated_at desc);
create index if not exists warranty_pdf_documents_customer_visible_idx on public.warranty_pdf_documents(customer_id, visible_to_customer, generation_status, created_at desc);
create index if not exists warranty_pdf_documents_storage_idx on public.warranty_pdf_documents(storage_bucket, storage_path);
create index if not exists warranties_customer_visible_idx on public.warranties(customer_id, visible_to_customer, created_at desc);
create index if not exists warranties_public_ref_idx on public.warranties(public_ref);

alter table public.warranty_pdf_documents enable row level security;

drop policy if exists "customers can read own visible warranty pdfs" on public.warranty_pdf_documents;
create policy "customers can read own visible warranty pdfs"
on public.warranty_pdf_documents for select
using (visible_to_customer = true and public.owns_customer(customer_id));

drop policy if exists "internal roles can read warranty pdfs" on public.warranty_pdf_documents;
create policy "internal roles can read warranty pdfs"
on public.warranty_pdf_documents for select
using (public.current_profile_role() in ('super_admin','operations_admin','finance','support'));

drop policy if exists "service role can write warranty pdfs" on public.warranty_pdf_documents;
create policy "service role can write warranty pdfs"
on public.warranty_pdf_documents for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
